M48
; DRILL file {KiCad 9.0.6} date 2026-09-15T03:16:16+0530
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-15T03:16:16+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X59.02Y-52.691
X59.02Y-142.691
X199.02Y-52.691
X199.02Y-142.691
M30
